//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCandyBotGames.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Orders = new HashSet<Order>();
        }

        [StringLength(256)]
        [Required(ErrorMessage = "Username is required")]
        public string Username { get; set; }

        [StringLength(160)]
        [Required(ErrorMessage = "First name is required")]
        public string FirstName { get; set; }

        [StringLength(160)]
        [Required(ErrorMessage = "Last name is required")]
        public string LastName { get; set; }

        [StringLength(70)]
        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        [StringLength(40)]
        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }

        [StringLength(40)]
        [Required(ErrorMessage = "State is required")]
        public string State { get; set; }

        [StringLength(10)]
        [Required(ErrorMessage = "Postal code is required")]
        public string PostalCode { get; set; }

        [StringLength(40)]
        [Required(ErrorMessage = "County is required")]
        public string Country { get; set; }

        [Phone]
        [StringLength(24)]
        [Required(ErrorMessage = "Phone is required")]
        public string Phone { get; set; }

        [EmailAddress]
        [StringLength(160)]
        [Required(ErrorMessage = "Email is required")]
        public string Email { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
